### ISSUE TITLE
Python 2.7 and Python 3 both failing 

### ISSUE THREAD

**Issue by cbelth** [Mri-monitoring/Mri-app#13]
When I run Mri-app with python 2.7, I get the following error:

`2016-10-04 11:32:35,854 [MainThread  ] [INFO ]  Log location at /net/kihara/cbelth/Mri-app/mri.log
2016-10-04 11:32:35,854 [MainThread  ] [INFO ]  Started MRI client at Tue Oct  4 11:32:35 2016
2016-10-04 11:32:35,855 [MainThread  ] [INFO ]  Read config file at config
2016-10-04 11:32:35,855 [MainThread  ] [DEBUG]  Generating retriever specified in config file
2016-10-04 11:32:36,114 [MainThread  ] [DEBUG]  Retrieving task '{'
Traceback (most recent call last):
  File "MriApp.py", line 25, in <module>
    main()
  File "MriApp.py", line 22, in main
    client.start()
  File "build/bdist.linux-x86_64/egg/mriapp/MriCaffe.py", line 59, in start
    self._retrieve = self._gen_retrieve()
  File "build/bdist.linux-x86_64/egg/mriapp/retrieve/LocalRetrieve.py", line 51, in retrieve_task
NameError: global name 'FileNotFoundError' is not defined`

I think this is because FileNotFoundError isn't available in Python 2.7, so I tried Python 3.

When I run the app with Python 3, I get this error:

`Traceback (most recent call last):
  File "MriApp.py", line 6, in <module>
    from future import standard_library
ImportError: No module named 'future'`

Any ideas?

**Comment by nharada1** [comment]
I will look into this once I get access to the testing machine. In the meantime, do you have the "future" package installed? It's a package to provide forward compatibility to py2 packages. Try "pip install future" to install it, or "pip3 install future" if you use Python 3.

**Comment by cbelth** [comment]
Ok, that worked for 'future.' However, now I get:

python3 MriApp.py
Traceback (most recent call last):
  File "MriApp.py", line 9, in <module>
    from mriapp.MriCaffe import MriCaffe
ImportError: No module named 'mriapp'`

The repo says mriapp should work with Python 2.7 and Python 3. Why does that 'FileNotFoundError' occur in Python 2.7?

**Comment by nharada1** [comment]
"future" is a dependency of the package. Have you installed all of the required packages? The error about not having "mriapp" makes me think you might not have installed all the requirements.

**Comment by cbelth** [comment]
I had to re-install the dependencies for Python 3.
